# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db56403c8aac309a84a21e84643a0ec2c5b3529b5b366244c2950f66899dccd77d2596ae74126d52e3277c31d6af5276173c8e296f4daf7be3ba4743634fcd69

test:
  secret_key_base: 2895af184770575c47fc9d03f48b4c695dc7e2d4778c1335a775a05eee1f2de1f83e0b0c87156e016ef10778ddfe77303c794549f6207846bcf7566b595858ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
